#!/usr/bin/python
import sys
from time import time
from optparse import OptionParser

from sudokulib.solver import SudokuSolver

if __name__ == '__main__':
    parser = OptionParser(usage='usage: %prog [options] source')
    parser.add_option('-f', '--free', dest='free_char', type='string',
                      help='The character signaling free place', default='.')
    (options, args) = parser.parse_args()

    if not len(args):
        print 'No source file provided'
        sys.exit(1)

    source = args[0]

    start_time = time()
    solver = SudokuSolver(source, verbosity=0,
                          free_char=options.free_char,
                          preprocessors=[], solvers=[],
                          backtracking=True)

    print '%s items missing' % solver.grid.missing

    solver.run()

    print solver
    print 'in %s seconds' % (time() - start_time)
    print '%s items missing' % solver.grid.missing
